dna:
  template-parameters-directory: "C:\\Develop\\Projects\\dna-app\\meta\\templated"
spring:
  application:
    name: dna-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portal
    username: vtw
    password: vtw123#
camel:
  main:
    routes-include-pattern: "file:meta/**/*.camel.yaml"
    shutdown-timeout: 1
  rest:
    binding-mode: json
  dataformat:
    jackson:
      auto-discover-object-mapper: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
