dna:
  meta-directory: "C:\\Develop\\Projects\\dna-app\\meta"
  template-parameters-directory: "${dna.meta-directory}\\templated"
  rest-errors-file: "${dna.meta-directory}\\rest\\rest-errors.yaml"
spring:
  application:
    name: dna-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/portal
    username: vtw
    password: vtw123#
mybatis:
  mapper-locations: classpath:mybatis/mappers/**/*.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
camel:
  main:
    routes-include-pattern: "file:meta/**/*.camel.yaml"
    shutdown-timeout: 1
  rest:
    binding-mode: json
  dataformat:
    jackson:
      auto-discover-object-mapper: true
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
